In [9]:
import numpy as np

In [10]:
data = np.random.randn(2,3)
data

array([[ 1.93024781, -0.57054401, -0.61860904],
       [-1.16725823,  1.7988533 , -0.54447891]])

In [11]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [24]:
data1 = np.ones((4,3))
data1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
data2 = np.array([1,2,3,4,5])

In [44]:
data2

array([1, 2, 3, 4, 5])

In [45]:
data2.dtype

dtype('int64')

In [51]:
data2.astype(float)

array([1., 2., 3., 4., 5.])

In [52]:
data3=np.array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [53]:
data3.astype(int)

array([ 3, -1, -2,  0, 12, 10])

In [54]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [55]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [66]:
import pandas as pd
obj = pd.Series([1,3,5,4.7,3.2], index=['a','b','e','c','d'])
obj

a    1.0
b    3.0
e    5.0
c    4.7
d    3.2
dtype: float64

In [67]:
obj.index

Index(['a', 'b', 'e', 'c', 'd'], dtype='object')

In [68]:
obj['e']

5.0

In [69]:
obj['f']=6
obj

a    1.0
b    3.0
e    5.0
c    4.7
d    3.2
f    6.0
dtype: float64

In [70]:
obj[['a','c','d']]

a    1.0
c    4.7
d    3.2
dtype: float64

In [71]:
np.exp(obj)

a      2.718282
b     20.085537
e    148.413159
c    109.947172
d     24.532530
f    403.428793
dtype: float64

In [72]:
sdata={'SaoPaulo':12000, 'MinasGerais':8000, 'RioJaneiro':10000, 'EspiritoSanto':6000}

In [97]:
obj3=pd.Series(sdata)
states=['California','RioJaneiro', 'EspiritoSanto','SaoPaulo']

In [98]:
obj3

SaoPaulo         12000
MinasGerais       8000
RioJaneiro       10000
EspiritoSanto     6000
dtype: int64

In [99]:
obj4 = pd.Series(sdata, index=states)
obj4

California           NaN
RioJaneiro       10000.0
EspiritoSanto     6000.0
SaoPaulo         12000.0
dtype: float64

In [100]:
obj4.isnull()

California        True
RioJaneiro       False
EspiritoSanto    False
SaoPaulo         False
dtype: bool

In [103]:
pd.notnull(obj4)

California       False
RioJaneiro        True
EspiritoSanto     True
SaoPaulo          True
dtype: bool

In [104]:
pd.isnull(obj4)

California        True
RioJaneiro       False
EspiritoSanto    False
SaoPaulo         False
dtype: bool

In [105]:
obj3+obj4

California           NaN
EspiritoSanto    12000.0
MinasGerais          NaN
RioJaneiro       20000.0
SaoPaulo         24000.0
dtype: float64

In [111]:
# obj4.name = 'population'
# obj4.index.name='state'
# obj4

In [113]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [115]:
pd.Series(data)

state    [Ohio, Ohio, Ohio, Nevada, Nevada, Nevada]
year           [2000, 2001, 2002, 2001, 2002, 2003]
pop                  [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
dtype: object

In [116]:
frame = pd.DataFrame(data)

In [117]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2